"""Autonomous engineering platform v2 foundation."""

from .code_editing import (
    CodeEditPlan,
    CodeEditingBackend,
    CodeEditingError,
    CodeEditingPolicy,
    CodeEditingWorkerRunResult,
    FileChange,
    GuardedCodeEditingWorker,
    LocalWorkspaceBackend,
    WorkspaceResult,
)
from .contracts import Job, JobState, RepositoryTarget
from .git_workspace import GitWorkspaceBackend
from .github_adapter import (
    DryRunMutationExecutor,
    GitHubAdapter,
    GitHubAdapterError,
    GuardedMutationExecutor,
    MutationCommand,
    MutationKind,
)
from .merger import (
    DryRunMergerAgent,
    MergeFinding,
    MergeReport,
    MergerAgent,
    MergerError,
    MergerRunResult,
)
from .orchestrator import DispatchResult, DryRunOrchestrator, Orchestrator, OrchestratorError
from .production_activation import (
    ActivationGate,
    ActivationStatus,
    GuardedProductionActivation,
    ProductionActivationConfig,
    ProductionActivationError,
    ProductionActivationReport,
    StaticProductionPreflight,
)
from .production_github import (
    GuardedGitHubMutationTransport,
    ProductionMutationConfig,
    ProductionMutationExecutor,
)
from .production_loop import (
    GuardedProductionLoop,
    IssueCycleResult,
    ProductionLoopConfig,
    ProductionLoopRunResult,
    ProductionLoopStatus,
    ReviewDecision,
)
from .rehearsal import (
    GuardedRehearsalRunner,
    RehearsalError,
    RehearsalGate,
    RehearsalReport,
    RehearsalStatus,
    StaticEmergencyStop,
)
from .reviewer import (
    DryRunReviewerAgent,
    ReviewFinding,
    ReviewReport,
    ReviewerAgent,
    ReviewerError,
    ReviewerRunResult,
)
from .scheduler import (
    BoundedScheduler,
    ProductionReadinessManifest,
    ScheduledDispatch,
    Scheduler,
    SchedulerConfig,
    SchedulerCycleResult,
    SchedulerLease,
    SchedulerMode,
)
from .store import JsonJobStore
from .validation import (
    SubprocessCommandRunner,
    ValidationCommand,
    ValidationRunResult,
    ValidationService,
    ValidationStatus,
    ValidationStepResult,
)
from .worker import DryRunWorkerAgent, WorkPlan, WorkerAgent, WorkerError, WorkerRunResult

__all__ = [
    "ActivationGate",
    "ActivationStatus",
    "BoundedScheduler",
    "CodeEditPlan",
    "CodeEditingBackend",
    "CodeEditingError",
    "CodeEditingPolicy",
    "CodeEditingWorkerRunResult",
    "DispatchResult",
    "DryRunMergerAgent",
    "DryRunMutationExecutor",
    "DryRunOrchestrator",
    "DryRunReviewerAgent",
    "DryRunWorkerAgent",
    "FileChange",
    "GitHubAdapter",
    "GitHubAdapterError",
    "GitWorkspaceBackend",
    "GuardedCodeEditingWorker",
    "GuardedGitHubMutationTransport",
    "GuardedMutationExecutor",
    "GuardedProductionActivation",
    "GuardedProductionLoop",
    "GuardedRehearsalRunner",
    "IssueCycleResult",
    "Job",
    "JobState",
    "JsonJobStore",
    "LocalWorkspaceBackend",
    "MergeFinding",
    "MergeReport",
    "MergerAgent",
    "MergerError",
    "MergerRunResult",
    "MutationCommand",
    "MutationKind",
    "Orchestrator",
    "OrchestratorError",
    "ProductionActivationConfig",
    "ProductionActivationError",
    "ProductionActivationReport",
    "ProductionLoopConfig",
    "ProductionLoopRunResult",
    "ProductionLoopStatus",
    "ProductionMutationConfig",
    "ProductionMutationExecutor",
    "ProductionReadinessManifest",
    "RehearsalError",
    "RehearsalGate",
    "RehearsalReport",
    "RehearsalStatus",
    "RepositoryTarget",
    "ReviewDecision",
    "ReviewFinding",
    "ReviewReport",
    "ReviewerAgent",
    "ReviewerError",
    "ReviewerRunResult",
    "ScheduledDispatch",
    "Scheduler",
    "SchedulerConfig",
    "SchedulerCycleResult",
    "SchedulerLease",
    "SchedulerMode",
    "StaticEmergencyStop",
    "StaticProductionPreflight",
    "SubprocessCommandRunner",
    "ValidationCommand",
    "ValidationRunResult",
    "ValidationService",
    "ValidationStatus",
    "ValidationStepResult",
    "WorkspaceResult",
    "WorkPlan",
    "WorkerAgent",
    "WorkerError",
    "WorkerRunResult",
]
